const $ = (id)=>document.getElementById(id);
let map, selectedLatLng=null, markersLayer, zonesLayer, selectMode=false, selectedIds=new Set();
const STORAGE='fishlog_v1_catches_restore';
const lureDb={
  'Soft Plastic Craw':['Strike King Rage Craw','Zoom Speed Craw','Berkley Chigger Craw','Missile Baits D Bomb','Other'],
  'Worm / Stick Bait':['Yamamoto Senko','Zoom Trick Worm','Zoom Ol Monster','Berkley Power Worm','Other'],
  'Jig':['Flipping Jig','Football Jig','Swim Jig','Finesse Jig','Other'],
  'Crankbait':['Bandit 100','Bandit 200','Bandit 300','Rapala DT6','Strike King 3XD','Other'],
  'Spinnerbait / Chatterbait':['Z-Man ChatterBait','Strike King Thunder Cricket','Booyah Spinnerbait','War Eagle Spinnerbait','Other'],
  'Topwater':['Whopper Plopper','Pop-R','Walking Bait','Buzzbait','Frog','Other'],
  'Other':['Other']
};
const colors=['Green Pumpkin','Black/Blue','PB&J','Watermelon Red','Junebug','Chartreuse/Black Back','Shad','Crawfish','White','Other'];
function getCatches(){return JSON.parse(localStorage.getItem(STORAGE)||'[]')}
function saveCatches(c){localStorage.setItem(STORAGE,JSON.stringify(c))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function initMap(){
  map=L.map('map',{zoomControl:false}).setView([38.03,-85.33],13);
  L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}).addTo(map);
  markersLayer=L.layerGroup().addTo(map); zonesLayer=L.layerGroup().addTo(map);
  map.on('click',e=>{selectedLatLng=e.latlng; updateChosenLocation(); $('logHereBtn').classList.remove('hidden'); $('locationHint').textContent='Manual spot selected — tap Log catch here';});
  setTimeout(()=>map.invalidateSize(),250); renderMap();
}
function updateChosenLocation(){ $('chosenLoc').textContent= selectedLatLng ? `Location set: ${selectedLatLng.lat.toFixed(5)}, ${selectedLatLng.lng.toFixed(5)}` : 'No location selected yet'; }
function fishIcon(big=false){ return L.divIcon({html:`<div class="fishMarker ${big?'bigMarker':''}">🐟</div>`,className:'',iconSize:[34,34],iconAnchor:[17,17]}); }
function clusterIcon(n){ return L.divIcon({html:`<div class="clusterMarker">${n}</div>`,className:'',iconSize:[44,44],iconAnchor:[22,22]}); }
function dist(a,b){const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,la1=a.lat*Math.PI/180,la2=b.lat*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLng/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function makeClusters(catches){ const clusters=[]; catches.forEach(c=>{let placed=false; for(const cl of clusters){ if(dist(c,cl.center)<70){cl.items.push(c); cl.center={lat:cl.items.reduce((s,i)=>s+i.lat,0)/cl.items.length,lng:cl.items.reduce((s,i)=>s+i.lng,0)/cl.items.length}; placed=true; break;} } if(!placed) clusters.push({center:{lat:c.lat,lng:c.lng},items:[c]}); }); return clusters; }
function renderMap(){ if(!markersLayer) return; markersLayer.clearLayers(); zonesLayer.clearLayers(); const catches=getCatches(); renderZones(catches); const clusters=makeClusters(catches); clusters.forEach(cl=>{ if(cl.items.length>1 && map.getZoom()<16){ const m=L.marker(cl.center,{icon:clusterIcon(cl.items.length)}).addTo(markersLayer); m.on('click touchstart',()=>{map.flyTo(cl.center,17,{duration:.6}); setTimeout(renderMap,650);}); } else { const biggest=cl.items.reduce((a,b)=>(Number(b.length||0)>Number(a.length||0)?b:a),cl.items[0]); cl.items.forEach(c=>{ const m=L.marker([c.lat,c.lng],{icon:fishIcon(c.id===biggest.id && cl.items.length>1)}).addTo(markersLayer); m.on('click touchstart',ev=>{ if(ev?.originalEvent) ev.originalEvent.preventDefault(); showFishCard(c.id); }); }); } }); renderHistory(); renderStats(); }
function renderZones(catches){ const bass=catches.filter(c=>/bass/i.test(c.species||'') && Number(c.length)>=15); const clusters=makeClusters(bass).filter(cl=>cl.items.length>=2); clusters.forEach(cl=>{ const avg=cl.items.reduce((s,i)=>s+Number(i.length||0),0)/cl.items.length; L.circle(cl.center,{radius:85,color:'#ffd166',weight:1,fillColor:'#ffd166',fillOpacity:Math.min(.10+cl.items.length*.04,.28)}).addTo(zonesLayer).bindTooltip(`Big Fish Zone: ${cl.items.length} bass 15”+ Avg ${avg.toFixed(1)}”`); }); }
function realisticBassSvg(){return `<svg viewBox="0 0 500 180" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="b" x1="0" x2="1"><stop stop-color="#344f2f"/><stop offset=".35" stop-color="#78a458"/><stop offset=".7" stop-color="#d9d9a8"/><stop offset="1" stop-color="#f2e9be"/></linearGradient></defs><path d="M38 92C86 34 210 18 333 48c46 11 76 29 105 48 24-24 45-39 61-42-12 30-20 52-18 74 0 17 4 33 14 53-25-10-44-24-59-43-53 25-120 34-192 27C132 154 65 127 38 92z" fill="url(#b)" stroke="#17351f" stroke-width="7"/><path d="M111 75c55-18 167-21 263 24-88-10-183-6-272 15" fill="none" stroke="#1f3521" stroke-width="12" opacity=".55"/><path d="M145 35c14 11 24 25 32 44" stroke="#284522" stroke-width="8"/><circle cx="88" cy="82" r="11" fill="#050807"/><path d="M67 107c31 6 63 5 90-2" stroke="#5b281e" stroke-width="8" fill="none"/><path d="M212 47l35-38 19 52M220 145l40 31 12-38" fill="#5c874a" stroke="#244021" stroke-width="5"/><path d="M116 122l35 28 2-37" fill="#6f9a4e" stroke="#244021" stroke-width="5"/></svg>`}
function showFishCard(id){ const c=getCatches().find(x=>x.id===id); if(!c) return; const hero=c.photo?`<img src="${c.photo}" class="catchPhoto">`:`<div class="bassHero">${/largemouth bass/i.test(c.species)?realisticBassSvg():'🐟'}</div>`; $('fishCardContent').innerHTML=`${hero}<h2>${c.species||'Fish'} ${Number(c.length)>=15 && /bass/i.test(c.species||'')?'<span class="zoneBadge">15”+ bass</span>':''}</h2><div class="metaGrid"><div class="meta"><b>Length</b><span>${c.length||'—'} in</span></div><div class="meta"><b>Weight</b><span>${c.weight||'—'} lb</span></div><div class="meta"><b>Lure</b><span>${c.lure||'—'}</span></div><div class="meta"><b>Color</b><span>${c.color||'—'}</span></div><div class="meta"><b>Depth/Cover</b><span>${c.depth||'—'}</span></div><div class="meta"><b>Date</b><span>${new Date(c.date).toLocaleDateString()}</span></div></div>${c.notes?`<p class="notes">${escapeHtml(c.notes)}</p>`:''}`; $('detailOverlay').classList.remove('hidden'); }
function closeCard(){ $('detailOverlay').classList.add('hidden'); }
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function showPage(id){ document.querySelectorAll('.page').forEach(p=>p.classList.remove('active')); $(id).classList.add('active'); document.querySelectorAll('.bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); if(id==='mapPage') setTimeout(()=>{map.invalidateSize();renderMap()},150); if(id==='historyPage') renderHistory(); if(id==='statsPage') renderStats(); }
function initLures(){ const lt=$('lureType'), le=$('lureExact'), lc=$('lureColor'); lt.innerHTML=Object.keys(lureDb).map(k=>`<option>${k}</option>`).join(''); lc.innerHTML=colors.map(k=>`<option>${k}</option>`).join(''); function fill(){le.innerHTML=lureDb[lt.value].map(k=>`<option>${k}</option>`).join(''); toggleCustom();} function toggleCustom(){ $('customLureBox').classList.toggle('hidden', le.value!=='Other'); } lt.onchange=fill; le.onchange=toggleCustom; fill(); }
function openLog(){ showPage('logPage'); updateChosenLocation(); }
function readPhoto(file){ return new Promise(res=>{ if(!file) return res(''); const r=new FileReader(); r.onload=e=>res(e.target.result); r.readAsDataURL(file); }); }
async function saveCatch(){ if(!selectedLatLng){ alert('Set a location first. Use GPS or tap the map.'); return; } const exact=$('lureExact').value==='Other' ? ($('customLure').value||'Other') : $('lureExact').value; const photo=await readPhoto($('photoInput').files[0]); const catchObj={id:uid(),species:$('species').value,length:$('length').value,weight:$('weight').value,lureType:$('lureType').value,lure:exact,color:$('lureColor').value,depth:$('depth').value,notes:$('notes').value,photo,lat:selectedLatLng.lat,lng:selectedLatLng.lng,date:new Date().toISOString()}; const catches=getCatches(); catches.push(catchObj); saveCatches(catches); clearForm(); showPage('mapPage'); renderMap(); }
function clearForm(){ ['length','weight','depth','notes','customLure'].forEach(id=>$(id).value=''); $('photoInput').value=''; $('photoPreview').classList.add('hidden'); }
function useGps(){ if(!navigator.geolocation){alert('GPS not available');return;} navigator.geolocation.getCurrentPosition(pos=>{ selectedLatLng={lat:pos.coords.latitude,lng:pos.coords.longitude}; updateChosenLocation(); $('logHereBtn').classList.remove('hidden'); map.flyTo(selectedLatLng,16); $('locationHint').textContent='GPS location set — tap Log catch here'; },err=>alert('Could not get GPS: '+err.message),{enableHighAccuracy:true,timeout:10000}); }
function hotspot(){ const catches=getCatches(); if(!catches.length){alert('No catches yet.');return;} const recent=catches.slice(-10); const big=recent.filter(c=>Number(c.length)>=15 && /bass/i.test(c.species)); const pool=big.length?big:recent; const lat=pool.reduce((s,c)=>s+c.lat,0)/pool.length, lng=pool.reduce((s,c)=>s+c.lng,0)/pool.length; map.flyTo([lat,lng],16,{duration:.8}); }
function renderHistory(){ const list=$('historyList'); if(!list) return; const catches=getCatches().slice().reverse(); list.innerHTML=catches.length?'':'<p style="color:#9fb7ae">No catches logged yet.</p>'; catches.forEach(c=>{ const row=document.createElement('div'); row.className='historyItem'; const thumb=c.photo?`<img class="historyThumb" src="${c.photo}">`:`<div class="historyThumb" style="display:flex;align-items:center;justify-content:center">🐟</div>`; row.innerHTML=`${selectMode?`<input class="checkBox" type="checkbox" ${selectedIds.has(c.id)?'checked':''}>`:thumb}<div><h3>${c.species||'Fish'} — ${c.length||'—'}”</h3><p>${c.lure||'No lure'} • ${new Date(c.date).toLocaleString()}</p></div><button class="ghostBtn">View</button>`; if(selectMode){ row.querySelector('input').onchange=e=>{ e.target.checked?selectedIds.add(c.id):selectedIds.delete(c.id); }; } row.querySelector('button').onclick=()=>{ showPage('mapPage'); setTimeout(()=>{map.flyTo([c.lat,c.lng],17); showFishCard(c.id);},250); }; list.appendChild(row); }); }
function renderStats(){ const catches=getCatches(); const biggest=catches.reduce((a,b)=>Number(b.length||0)>Number(a?.length||0)?b:a,null); const bass15=catches.filter(c=>/bass/i.test(c.species||'')&&Number(c.length)>=15).length; $('statsContent').innerHTML=`<h2>${catches.length} catches logged</h2><p>Big Fish Zone qualifiers: <b>${bass15}</b> bass 15”+</p><p>Biggest fish: <b>${biggest?`${biggest.length}” ${biggest.species}`:'—'}</b></p><p>Most recent lure: <b>${catches.at(-1)?.lure||'—'}</b></p>`; }
function deleteSelected(){ const remaining=getCatches().filter(c=>!selectedIds.has(c.id)); saveCatches(remaining); selectedIds.clear(); renderMap(); renderHistory(); }
function bind(){ document.querySelectorAll('.bottomNav button[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page)); $('openLog').onclick=()=>openLog(); $('logHereBtn').onclick=()=>openLog(); $('gpsBtn').onclick=useGps; $('hotBtn').onclick=hotspot; $('useGpsInForm').onclick=useGps; $('saveCatch').onclick=saveCatch; $('cancelLog').onclick=()=>showPage('mapPage'); $('cancelLogTop').onclick=()=>showPage('mapPage'); $('closeCard').onclick=closeCard; $('detailOverlay').addEventListener('click',e=>{ if(e.target.id==='detailOverlay') closeCard(); }); $('photoInput').onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=ev=>{ $('photoPreview').src=ev.target.result; $('photoPreview').classList.remove('hidden'); }; r.readAsDataURL(f); }; $('selectModeBtn').onclick=()=>{selectMode=true; $('bulkBar').classList.remove('hidden'); renderHistory();}; $('doneSelectBtn').onclick=()=>{selectMode=false; selectedIds.clear(); $('bulkBar').classList.add('hidden'); renderHistory();}; $('selectAllBtn').onclick=()=>{getCatches().forEach(c=>selectedIds.add(c.id)); renderHistory();}; $('deleteSelectedBtn').onclick=()=>{ if(selectedIds.size && confirm(`Delete ${selectedIds.size} selected catches?`)) deleteSelected();}; }
window.addEventListener('load',()=>{initLures(); bind(); initMap(); updateChosenLocation();});
