const STORAGE_KEY='fishlog_catches_v14_clean';
let map, selectedLatLng=null, markersLayer, zoneLayer, selectMode=false, selectedIds=new Set(), photoData='';
const lureData={
  'Soft Plastic Craw':['Strike King Rage Craw','Zoom Speed Craw','Berkley Chigger Craw','NetBait Paca Craw','Googan Bandito Bug','Other'],
  'Creature Bait':['Zoom Brush Hog','Missile Baits D Bomb','Reaction Innovations Sweet Beaver','Yum Christie Critter','Bronco Bug','Other'],
  'Worm / Stick Bait':['Yamamoto Senko','Yum Dinger','Zoom Trick Worm','Roboworm','Berkley MaxScent The General','Other'],
  'Jig':['Flipping Jig','Football Jig','Swim Jig','Finesse Jig','Casting Jig','Other'],
  'Crankbait':['Bandit 100','Bandit 200','Bandit 300','Rapala DT6','Rapala DT10','Strike King Series 3','Strike King 6XD','Other'],
  'Spinnerbait / Bladed Jig':['Z-Man ChatterBait','Strike King Thunder Cricket','Booyah Spinnerbait','War Eagle Spinnerbait','Other'],
  'Topwater':['Whopper Plopper','Heddon Spook','Pop-R','Buzzbait','Frog','Other'],
  'Other':['Other']
};
const colors=['Green Pumpkin','Black/Blue','Watermelon Red','Junebug','White','Chartreuse/Black Back','Sexy Shad','Crawfish','PB&J','Natural Shad','Other'];
function $(id){return document.getElementById(id)}
function getCatches(){return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}
function saveCatches(c){localStorage.setItem(STORAGE_KEY,JSON.stringify(c))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function bassSvg(){return `<svg class="cartoonBassSvg" viewBox="0 0 520 230" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#2fb86e"/><stop offset=".55" stop-color="#7ccf6b"/><stop offset="1" stop-color="#d8e66a"/></linearGradient><filter id="s" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="9" stdDeviation="8" flood-color="#000" flood-opacity=".35"/></filter></defs><ellipse cx="258" cy="128" rx="160" ry="62" fill="url(#g)" filter="url(#s)"/><path d="M101 122 L32 69 C20 101 21 151 34 181 Z" fill="#2a935f"/><path d="M365 104 C420 63 477 72 498 113 C455 120 421 139 379 158 Z" fill="#6fc96a"/><path d="M365 148 C420 190 475 181 499 139 C454 134 416 122 379 99 Z" fill="#55ad62" opacity=".95"/><path d="M210 67 C248 30 307 29 337 78 C291 70 250 72 210 67Z" fill="#248c59"/><path d="M245 188 C274 216 327 205 349 162 C308 176 275 185 245 188Z" fill="#248c59"/><ellipse cx="388" cy="121" rx="66" ry="56" fill="#8bd76c"/><circle cx="421" cy="105" r="12" fill="#101414"/><circle cx="425" cy="101" r="4" fill="#fff"/><path d="M425 136 C398 151 372 148 350 135" stroke="#123" stroke-width="7" fill="none" stroke-linecap="round"/><path d="M90 125 C143 103 220 100 333 116" stroke="#17391f" stroke-width="8" opacity=".45" fill="none" stroke-linecap="round"/><g fill="#174926" opacity=".55"><circle cx="147" cy="105" r="5"/><circle cx="178" cy="126" r="5"/><circle cx="210" cy="102" r="4"/><circle cx="244" cy="135" r="5"/><circle cx="285" cy="111" r="4"/></g><text x="260" y="222" text-anchor="middle" font-size="24" font-weight="800" fill="#e9fbff">Largemouth Bass</text></svg>`}
function initMap(){
 map=L.map('map',{zoomControl:false,attributionControl:true}).setView([38.064,-85.448],14);
 L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}).addTo(map);
 markersLayer=L.layerGroup().addTo(map); zoneLayer=L.layerGroup().addTo(map);
 map.on('click',e=>{selectedLatLng=e.latlng; updateLocationText(); toast('Manual catch location set');});
 setTimeout(()=>map.invalidateSize(),300);
 renderMap();
}
function fishIcon(big=false){return L.divIcon({className: big?'bigFishMarker':'', html:`<div class="markerFish"><span>${big?'🏆':'🐟'}</span></div>`, iconSize:[34,34], iconAnchor:[17,28]})}
function clusterIcon(n){return L.divIcon({className:'',html:`<div class="clusterMarker">${n}</div>`,iconSize:[42,42],iconAnchor:[21,21]})}
function dist(a,b){const R=6371000, p=Math.PI/180; const dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p; const x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2; return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function clusters(catches){const out=[]; const used=new Set(); const radius=80; catches.forEach((c,i)=>{if(used.has(i))return; const group=[c]; used.add(i); catches.forEach((d,j)=>{if(!used.has(j)&&dist(c,d)<radius){group.push(d);used.add(j)}}); out.push(group)}); return out}
function renderMap(){if(!markersLayer)return; markersLayer.clearLayers(); zoneLayer.clearLayers(); const catches=getCatches().filter(c=>c.lat&&c.lng); clusters(catches).forEach(g=>{ if(g.length>1 && map.getZoom()<17){ const lat=g.reduce((s,c)=>s+c.lat,0)/g.length,lng=g.reduce((s,c)=>s+c.lng,0)/g.length; L.marker([lat,lng],{icon:clusterIcon(g.length)}).addTo(markersLayer).on('click',()=>{map.flyTo([lat,lng],18,{duration:.7}); setTimeout(renderMap,760)}); } else { const biggest=[...g].sort((a,b)=>(+b.length||0)-(+a.length||0))[0]; g.forEach(c=>{const m=L.marker([c.lat,c.lng],{icon:fishIcon(c.id===biggest.id && g.length>1)}).addTo(markersLayer); m.on('click touchstart',ev=>{if(ev?.originalEvent)L.DomEvent.stopPropagation(ev); showCard(c)});}); }}); renderZones(catches); }
function renderZones(catches){const bass=catches.filter(c=>/bass/i.test(c.species||'') && (+c.length||0)>=15); clusters(bass).filter(g=>g.length>=2).forEach(g=>{ const lat=g.reduce((s,c)=>s+c.lat,0)/g.length,lng=g.reduce((s,c)=>s+c.lng,0)/g.length; L.circle([lat,lng],{radius:70,color:'rgba(247,201,72,.45)',fillColor:'rgba(247,201,72,.18)',fillOpacity:.35,weight:2}).addTo(zoneLayer).on('click',()=>showZone(g)); });}
function showCard(c){ const hero=$('cardHero'); hero.innerHTML=c.photo?`<img src="${c.photo}" alt="catch photo">`:bassSvg(); $('cardContent').innerHTML=`<h2>${c.species||'Fish'}</h2><div class="historySub">${new Date(c.date).toLocaleString()}</div><div class="metaGrid"><div class="meta"><b>${c.length||'-'} in</b><span>Length</span></div><div class="meta"><b>${c.weight||'-'} lb</b><span>Weight</span></div><div class="meta"><b>${c.lure||'-'}</b><span>Lure</span></div><div class="meta"><b>${c.depth||'-'} ft</b><span>Depth</span></div></div>${c.notes?`<p>${escapeHtml(c.notes)}</p>`:''}`; $('detailOverlay').classList.remove('hidden'); }
function showZone(g){ const biggest=[...g].sort((a,b)=>(+b.length||0)-(+a.length||0))[0]; $('cardHero').innerHTML=bassSvg(); $('cardContent').innerHTML=`<h2>Big Fish Zone</h2><div class="historySub">${g.length} bass 15 inches or larger</div><div class="metaGrid"><div class="meta"><b>${biggest.length} in</b><span>Largest</span></div><div class="meta"><b>${avg(g.map(x=>+x.length||0)).toFixed(1)} in</b><span>Avg Length</span></div><div class="meta"><b>${top(g.map(x=>x.lure))}</b><span>Best Lure</span></div><div class="meta"><b>${g.length}</b><span>Catches</span></div></div>`; $('detailOverlay').classList.remove('hidden');}
function avg(a){return a.reduce((s,x)=>s+x,0)/(a.length||1)} function top(a){const m={};a.filter(Boolean).forEach(x=>m[x]=(m[x]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'-'}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); if(id==='mapPage')setTimeout(()=>{map.invalidateSize();renderMap()},120); if(id==='historyPage')renderHistory(); if(id==='statsPage')renderStats();}
function updateLocationText(){const txt=selectedLatLng?`${selectedLatLng.lat.toFixed(5)}, ${selectedLatLng.lng.toFixed(5)}`:'No location selected'; $('locationText').textContent=txt;}
function populateLures(){const lt=$('lureType'); lt.innerHTML=Object.keys(lureData).map(x=>`<option>${x}</option>`).join(''); $('lureColor').innerHTML=colors.map(x=>`<option>${x}</option>`).join(''); updateExact();}
function updateExact(){const type=$('lureType').value; $('lureExact').innerHTML=(lureData[type]||['Other']).map(x=>`<option>${x}</option>`).join(''); updateCustom();}
function updateCustom(){ $('customLureWrap').classList.toggle('hidden',$('lureExact').value!=='Other');}
function clearForm(){['length','weight','depth','notes','customLure'].forEach(id=>$(id).value=''); photoData=''; $('photoPreview').classList.add('hidden'); $('photoInput').value='';}
function saveCatch(){ if(!selectedLatLng){toast('Pick a map spot or use GPS first');showPage('mapPage');return;} const exact=$('lureExact').value==='Other'?$('customLure').value.trim()||'Other':$('lureExact').value; const lure=`${exact} - ${$('lureColor').value}`; const c={id:uid(),date:new Date().toISOString(),lat:selectedLatLng.lat,lng:selectedLatLng.lng,species:$('species').value,length:$('length').value,weight:$('weight').value,lureType:$('lureType').value,lure,depth:$('depth').value,notes:$('notes').value,photo:photoData}; const all=getCatches(); all.push(c); saveCatches(all); clearForm(); renderMap(); renderHistory(); toast('Catch saved'); showPage('mapPage');}
function useGps(){ if(!navigator.geolocation){toast('GPS unavailable');return;} toast('Getting GPS...'); navigator.geolocation.getCurrentPosition(pos=>{selectedLatLng=L.latLng(pos.coords.latitude,pos.coords.longitude); updateLocationText(); map.flyTo(selectedLatLng,17); toast('GPS location set');},()=>toast('GPS permission failed'),{enableHighAccuracy:true,timeout:10000});}
function renderHistory(){const list=$('historyList'), catches=getCatches().slice().reverse(); if(!catches.length){list.innerHTML='<div class="historySub">No catches logged yet.</div>';return;} list.innerHTML=catches.map(c=>`<div class="historyItem" data-id="${c.id}">${selectMode?`<input type="checkbox" ${selectedIds.has(c.id)?'checked':''}>`:''}<div class="thumb">${c.photo?`<img class="thumb" src="${c.photo}">`:'🐟'}</div><div><div class="historyTitle">${c.species||'Fish'} ${c.length?`• ${c.length} in`:''}</div><div class="historySub">${c.lure||''}<br>${new Date(c.date).toLocaleDateString()}</div></div><div>›</div></div>`).join(''); list.querySelectorAll('.historyItem').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.id; if(selectMode){selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);renderHistory();}else{const c=getCatches().find(x=>x.id===id); if(c){showPage('mapPage');map.flyTo([c.lat,c.lng],18);setTimeout(()=>showCard(c),400)}}})); }
function renderStats(){const c=getCatches(); const biggest=[...c].sort((a,b)=>(+b.length||0)-(+a.length||0))[0]; $('statsBody').innerHTML=`<div class="metaGrid"><div class="meta"><b>${c.length}</b><span>Total Catches</span></div><div class="meta"><b>${biggest?.length||'-'} in</b><span>Biggest</span></div><div class="meta"><b>${top(c.map(x=>x.lure))}</b><span>Top Lure</span></div><div class="meta"><b>${c.filter(x=>/bass/i.test(x.species||'')&&(+x.length||0)>=15).length}</b><span>15”+ Bass</span></div></div>`;}
function deleteSelected(){const keep=getCatches().filter(c=>!selectedIds.has(c.id)); saveCatches(keep); selectedIds.clear(); renderHistory(); renderMap(); toast('Deleted selected catches');}
function hotspot(){const c=getCatches().filter(x=>x.lat&&x.lng); if(!c.length){toast('No catches yet');return;} const g=clusters(c).sort((a,b)=>b.length-a.length || ((+b[0].length||0)-(+a[0].length||0)))[0]; const lat=g.reduce((s,x)=>s+x.lat,0)/g.length,lng=g.reduce((s,x)=>s+x.lng,0)/g.length; map.flyTo([lat,lng],17,{duration:.8}); toast('Hotspot found');}
function wire(){document.querySelectorAll('.navBtn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page))); $('openLogBtn').onclick=()=>showPage('logPage'); $('cancelLogTop').onclick=()=>showPage('mapPage'); $('saveCatchTop').onclick=saveCatch; $('gpsBtn').onclick=useGps; $('hotspotBtn').onclick=hotspot; $('useGpsFromForm').onclick=useGps; $('backToMapForPin').onclick=()=>showPage('mapPage'); $('closeCard').onclick=()=>$('detailOverlay').classList.add('hidden'); $('detailOverlay').addEventListener('click',e=>{if(e.target.id==='detailOverlay')$('detailOverlay').classList.add('hidden')}); $('lureType').onchange=updateExact; $('lureExact').onchange=updateCustom; $('photoInput').onchange=e=>{const file=e.target.files?.[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{photoData=r.result; $('photoPreview').src=photoData; $('photoPreview').classList.remove('hidden')}; r.readAsDataURL(file);}; $('selectModeBtn').onclick=()=>{selectMode=!selectMode; $('selectModeBtn').textContent=selectMode?'Done':'Select'; $('deleteSelectedBtn').classList.toggle('hidden',!selectMode); $('selectTools').classList.toggle('hidden',!selectMode); renderHistory();}; $('selectAllBtn').onclick=()=>{getCatches().forEach(c=>selectedIds.add(c.id));renderHistory();}; $('clearSelectedBtn').onclick=()=>{selectedIds.clear();renderHistory();}; $('deleteSelectedBtn').onclick=deleteSelected;}
window.addEventListener('load',()=>{populateLures();wire();initMap();updateLocationText();renderHistory();renderStats();});
